name: 🐞 Bug Report
title: '[bug] '
description: Report a detailed bug
labels: ['type: bug']

body:
  - type: markdown
    attributes:
      value: |
        ## Before submitting
        1. Search [NovaFlow/issues](https://github.com/drewsephski/NovaFlow/issues) to check if this bug already exists.
        2. Try downloading the latest version of NovaFlow to see if the issue persists.
        3. Make sure this is an App issue, not an AI or agent issue.
        4. Describe the bug in detail with comprehensive information.
        5. Be friendly in the community.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Describe the bug in detail, including reproduction steps, expected behavior, and actual behavior. Screenshots or videos are appreciated.
      placeholder: Bug description
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: NovaFlow version
      placeholder: Enter your current NovaFlow version.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Error logs
      description: Right-click to open developer tools and paste error messages here.
      placeholder: Bug logs
