name: 💡 Feature Request
title: '[feat] '
description: Have a great idea?
labels: ['type: feat']

body:
  - type: textarea
    id: problem
    attributes:
      label: Describe your suggestion
      description: Clearly describe what problem this suggestion would solve
    validations:
      required: true